// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatientService.Infrastructure.Persistence;

#nullable disable

namespace PatientService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    [Migration("20260822203936_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatientService.Domain.Entities.Allergy", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_ALLERGY");

                    b.ToTable("Allergies", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.BloodType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_BLOOD_TYPE");

                    b.ToTable("BloodTypes", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Condition", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_CONDITION");

                    b.ToTable("Conditions", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.ConsentType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_CONSENT_TYPE");

                    b.ToTable("ConsentTypes", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Gender", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_GENDER");

                    b.ToTable("Genders", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.InsurancePayer", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_INSURANCE_PAYER");

                    b.ToTable("InsurancePayers", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_LANGUAGE");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("AddressLine")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("AddressLine");

                    b.Property<Guid?>("AssignedDoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("AssignedDoctorId");

                    b.Property<string>("BloodTypeCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("BloodTypeCode");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("CurrentHealthInstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("CurrentHealthInstitutionId");

                    b.Property<string>("CurrentInstitutionName")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CurrentInstitutionName");

                    b.Property<string>("CurrentInsurancePayerCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CurrentInsurancePayerCode");

                    b.Property<string>("CurrentInsurancePolicyNumber")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CurrentInsurancePolicyNumber");

                    b.Property<string>("CurrentStatusCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CurrentStatusCode");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FirstName");

                    b.Property<string>("GenderCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("GenderCode");

                    b.Property<decimal?>("HeightCm")
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("HeightCm");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp")
                        .HasColumnName("LastActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LastName");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("int")
                        .HasColumnName("MunicipalityId");

                    b.Property<string>("NationalId")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NationalId");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("Notes");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Phone");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ProfilePictureUrl");

                    b.Property<int?>("SettlementId")
                        .HasColumnType("int")
                        .HasColumnName("SettlementId");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric(5,1)")
                        .HasColumnName("WeightKg");

                    b.HasKey("Id")
                        .HasName("PK_PATIENT");

                    b.HasIndex("AssignedDoctorId")
                        .HasDatabaseName("IX_PATIENT_ASSIGNED_DOCTOR");

                    b.HasIndex("BloodTypeCode")
                        .HasDatabaseName("IX_PATIENT_BLOOD_TYPE");

                    b.HasIndex("CurrentInsurancePayerCode");

                    b.HasIndex("CurrentStatusCode")
                        .HasDatabaseName("IX_PATIENT_STATUS");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_PATIENT_EMAIL");

                    b.HasIndex("GenderCode")
                        .HasDatabaseName("IX_PATIENT_GENDER");

                    b.HasIndex("LastName")
                        .HasDatabaseName("IX_PATIENT_LASTNAME");

                    b.HasIndex("NationalId")
                        .IsUnique()
                        .HasDatabaseName("UX_PATIENT_NATIONAL_ID")
                        .HasFilter("\"NationalId\" IS NOT NULL");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientAffiliationHistory", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<int?>("HealthInstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("HealthInstitutionId");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("InstitutionName");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("PatientId", "SequenceNumber")
                        .HasName("PK_PATIENT_AFFILIATION_HISTORY");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_PATIENT_AFFILIATION_HISTORY_PATIENT");

                    b.ToTable("PatientAffiliationHistories", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientAllergyCoverage", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<string>("AllergyCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("AllergyCode");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Note");

                    b.HasKey("PatientId", "AllergyCode")
                        .HasName("PK_PATIENT_ALLERGY_COVERAGE");

                    b.HasIndex("AllergyCode")
                        .HasDatabaseName("IX_PATIENT_ALLERGY_COVERAGE_ALLERGY");

                    b.ToTable("PatientAllergyCoverages", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientConditionCoverage", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<string>("ConditionCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ConditionCode");

                    b.Property<decimal?>("DiagnosedYear")
                        .HasColumnType("numeric(4,0)")
                        .HasColumnName("DiagnosedYear");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Note");

                    b.HasKey("PatientId", "ConditionCode")
                        .HasName("PK_PATIENT_CONDITION_COVERAGE");

                    b.HasIndex("ConditionCode")
                        .HasDatabaseName("IX_PATIENT_CONDITION_COVERAGE_CONDITION");

                    b.ToTable("PatientConditionCoverages", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientConsentCoverage", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<string>("ConsentTypeCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ConsentTypeCode");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("PatientId", "ConsentTypeCode")
                        .HasName("PK_PATIENT_CONSENT_COVERAGE");

                    b.HasIndex("ConsentTypeCode")
                        .HasDatabaseName("IX_PATIENT_CONSENT_COVERAGE_TYPE");

                    b.ToTable("PatientConsentCoverages", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientDoctorAssignmentHistory", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("PatientId", "SequenceNumber")
                        .HasName("PK_PATIENT_DOCTOR_ASSIGNMENT_HISTORY");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_PATIENT_DOCTOR_ASSIGNMENT_HISTORY_DOCTOR");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_PATIENT_DOCTOR_ASSIGNMENT_HISTORY_PATIENT");

                    b.ToTable("PatientDoctorAssignmentHistories", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientEmergencyContact", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("FullName");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Phone");

                    b.Property<string>("RelationshipCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("RelationshipCode");

                    b.HasKey("PatientId", "SequenceNumber")
                        .HasName("PK_PATIENT_EMERGENCY_CONTACT");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_PATIENT_EMERGENCY_CONTACT_PATIENT");

                    b.HasIndex("RelationshipCode")
                        .HasDatabaseName("IX_PATIENT_EMERGENCY_CONTACT_RELATIONSHIP");

                    b.ToTable("PatientEmergencyContacts", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientInsuranceHistory", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<string>("PayerCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PayerCode");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PolicyNumber");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("PatientId", "SequenceNumber")
                        .HasName("PK_PATIENT_INSURANCE_HISTORY");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_PATIENT_INSURANCE_HISTORY_PATIENT");

                    b.HasIndex("PayerCode")
                        .HasDatabaseName("IX_PATIENT_INSURANCE_HISTORY_PAYER");

                    b.ToTable("PatientInsuranceHistories", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientLanguageCoverage", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("LanguageCode");

                    b.HasKey("PatientId", "LanguageCode")
                        .HasName("PK_PATIENT_LANGUAGE_COVERAGE");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("IX_PATIENT_LANGUAGE_COVERAGE_LANGUAGE");

                    b.ToTable("PatientLanguageCoverages", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_PATIENT_STATUS");

                    b.ToTable("PatientStatuses", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientStatusHistory", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("StatusCode");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("PatientId", "SequenceNumber")
                        .HasName("PK_PATIENT_STATUS_HISTORY");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_PATIENT_STATUS_HISTORY_PATIENT");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("IX_PATIENT_STATUS_HISTORY_STATUS");

                    b.ToTable("PatientStatusHistories", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.RelationshipType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_RELATIONSHIP_TYPE");

                    b.ToTable("RelationshipTypes", (string)null);
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Patient", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.BloodType", "BloodType")
                        .WithMany("Patients")
                        .HasForeignKey("BloodTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PATIENT_BLOOD_TYPE");

                    b.HasOne("PatientService.Domain.Entities.InsurancePayer", "CurrentInsurancePayer")
                        .WithMany()
                        .HasForeignKey("CurrentInsurancePayerCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PATIENT_INSURANCE_PAYER");

                    b.HasOne("PatientService.Domain.Entities.PatientStatus", "Status")
                        .WithMany("Patients")
                        .HasForeignKey("CurrentStatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_STATUS");

                    b.HasOne("PatientService.Domain.Entities.Gender", "Gender")
                        .WithMany("Patients")
                        .HasForeignKey("GenderCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_GENDER");

                    b.Navigation("BloodType");

                    b.Navigation("CurrentInsurancePayer");

                    b.Navigation("Gender");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientAffiliationHistory", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.Patient", "Patient")
                        .WithMany("AffiliationHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_AFFILIATION_HISTORY_PATIENT");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientAllergyCoverage", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.Allergy", "Allergy")
                        .WithMany("Coverages")
                        .HasForeignKey("AllergyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_ALLERGY_COVERAGE_ALLERGY");

                    b.HasOne("PatientService.Domain.Entities.Patient", "Patient")
                        .WithMany("AllergyCoverages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_ALLERGY_COVERAGE_PATIENT");

                    b.Navigation("Allergy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientConditionCoverage", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.Condition", "Condition")
                        .WithMany("Coverages")
                        .HasForeignKey("ConditionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_CONDITION_COVERAGE_CONDITION");

                    b.HasOne("PatientService.Domain.Entities.Patient", "Patient")
                        .WithMany("ConditionCoverages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_CONDITION_COVERAGE_PATIENT");

                    b.Navigation("Condition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientConsentCoverage", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.ConsentType", "ConsentType")
                        .WithMany("Coverages")
                        .HasForeignKey("ConsentTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_CONSENT_COVERAGE_TYPE");

                    b.HasOne("PatientService.Domain.Entities.Patient", "Patient")
                        .WithMany("ConsentCoverages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_CONSENT_COVERAGE_PATIENT");

                    b.Navigation("ConsentType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientDoctorAssignmentHistory", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.Patient", "Patient")
                        .WithMany("DoctorAssignmentHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_DOCTOR_ASSIGNMENT_HISTORY_PATIENT");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientEmergencyContact", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.Patient", "Patient")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_EMERGENCY_CONTACT_PATIENT");

                    b.HasOne("PatientService.Domain.Entities.RelationshipType", "Relationship")
                        .WithMany("Contacts")
                        .HasForeignKey("RelationshipCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_EMERGENCY_CONTACT_RELATIONSHIP");

                    b.Navigation("Patient");

                    b.Navigation("Relationship");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientInsuranceHistory", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.Patient", "Patient")
                        .WithMany("InsuranceHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_INSURANCE_HISTORY_PATIENT");

                    b.HasOne("PatientService.Domain.Entities.InsurancePayer", "Payer")
                        .WithMany("Histories")
                        .HasForeignKey("PayerCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_INSURANCE_HISTORY_PAYER");

                    b.Navigation("Patient");

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientLanguageCoverage", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.Language", "Language")
                        .WithMany("Coverages")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_LANGUAGE_COVERAGE_LANGUAGE");

                    b.HasOne("PatientService.Domain.Entities.Patient", "Patient")
                        .WithMany("LanguageCoverages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_LANGUAGE_COVERAGE_PATIENT");

                    b.Navigation("Language");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientStatusHistory", b =>
                {
                    b.HasOne("PatientService.Domain.Entities.Patient", "Patient")
                        .WithMany("StatusHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_STATUS_HISTORY_PATIENT");

                    b.HasOne("PatientService.Domain.Entities.PatientStatus", "Status")
                        .WithMany("Histories")
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_STATUS_HISTORY_STATUS");

                    b.Navigation("Patient");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Allergy", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.BloodType", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Condition", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.ConsentType", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Gender", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.InsurancePayer", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Language", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.Patient", b =>
                {
                    b.Navigation("AffiliationHistories");

                    b.Navigation("AllergyCoverages");

                    b.Navigation("ConditionCoverages");

                    b.Navigation("ConsentCoverages");

                    b.Navigation("DoctorAssignmentHistories");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("InsuranceHistories");

                    b.Navigation("LanguageCoverages");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.PatientStatus", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("PatientService.Domain.Entities.RelationshipType", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
