global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: identity
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:6000"]
        labels:
          service: identityservice-api

  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5000"]
        labels:
          service: gateway-api

  - job_name: mail
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:6001"]
        labels:
          service: mailservice-api

  - job_name: pdf
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:6002"]
        labels:
          service: pdfservice-api

  - job_name: location
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:6003"]
        labels:
          service: locationservice-api

  - job_name: doctor
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:6004"]
        labels:
          service: doctorservice-api

  - job_name: patient
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:6005"]
        labels:
          service: patientservice-api
