// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("HealthInstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("HealthInstitutionId");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(512)")
                        .HasColumnName("Message");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("Payload");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("ReadAt");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("RecipientUserId");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("RelatedEntityId");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RelatedEntityType");

                    b.Property<string>("SeverityCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SeverityCode");

                    b.Property<Guid?>("SourceEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("SourceEventId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Title");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TypeCode");

                    b.HasKey("Id")
                        .HasName("PK_NOTIFICATION");

                    b.HasIndex("RecipientUserId")
                        .HasDatabaseName("IX_NOTIFICATION_RECIPIENT_UNREAD")
                        .HasFilter("\"ReadAt\" IS NULL");

                    b.HasIndex("SeverityCode")
                        .HasDatabaseName("IX_NOTIFICATION_SEVERITY");

                    b.HasIndex("SourceEventId")
                        .IsUnique()
                        .HasDatabaseName("UX_NOTIFICATION_SOURCE_EVENT")
                        .HasFilter("\"SourceEventId\" IS NOT NULL");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("IX_NOTIFICATION_TYPE");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_NOTIFICATION_RECIPIENT_CREATED");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationChannel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_NOTIFICATION_CHANNEL");

                    b.ToTable("NotificationChannels", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.Property<string>("TypeCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TypeCode");

                    b.Property<string>("ChannelCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ChannelCode");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("Enabled");

                    b.HasKey("UserId", "TypeCode", "ChannelCode")
                        .HasName("PK_NOTIFICATION_PREFERENCE");

                    b.HasIndex("ChannelCode")
                        .HasDatabaseName("IX_NOTIFICATION_PREFERENCE_CHANNEL");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("IX_NOTIFICATION_PREFERENCE_TYPE");

                    b.ToTable("NotificationPreferences", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationSeverity", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_NOTIFICATION_SEVERITY");

                    b.ToTable("NotificationSeverities", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_NOTIFICATION_TYPE");

                    b.ToTable("NotificationTypes", (string)null);
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.Notification", b =>
                {
                    b.HasOne("NotificationService.Domain.Entities.NotificationSeverity", "Severity")
                        .WithMany("Notifications")
                        .HasForeignKey("SeverityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NOTIFICATION_SEVERITY");

                    b.HasOne("NotificationService.Domain.Entities.NotificationType", "Type")
                        .WithMany("Notifications")
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NOTIFICATION_TYPE");

                    b.Navigation("Severity");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationPreference", b =>
                {
                    b.HasOne("NotificationService.Domain.Entities.NotificationChannel", "Channel")
                        .WithMany("Preferences")
                        .HasForeignKey("ChannelCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NOTIFICATION_PREFERENCE_CHANNEL");

                    b.HasOne("NotificationService.Domain.Entities.NotificationType", "Type")
                        .WithMany("Preferences")
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_NOTIFICATION_PREFERENCE_TYPE");

                    b.Navigation("Channel");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationChannel", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationSeverity", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("NotificationService.Domain.Entities.NotificationType", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
