<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f3a8c2d1-9b4e-4a7f-8c6d-1e2f3a4b5c6d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks\BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\..\neurovision.ai.ServiceDefaults\neurovision.ai.ServiceDefaults.csproj" />
    <ProjectReference Include="..\TumorDetectionService.Application\TumorDetectionService.Application.csproj" />
    <ProjectReference Include="..\TumorDetectionService.Infrastructure\TumorDetectionService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\scans\" />
    <Folder Include="wwwroot\reports\" />
  </ItemGroup>

</Project>
