// <auto-generated />
using System;
using LocationService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LocationService.Infrastructure.Migrations
{
    [DbContext(typeof(LocationDbContext))]
    [Migration("20260723135129_fix2")]
    partial class fix2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LocationService.Domain.Entities.Capital", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<int>("SettlementCode")
                        .HasColumnType("int")
                        .HasColumnName("SettlementCode");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(1,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("CountryCode", "SettlementCode", "SequenceNumber")
                        .HasName("PK_CAPITAL");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("IX_CAPITAL_COUNTRY");

                    b.HasIndex("CountryCode", "SettlementCode")
                        .HasDatabaseName("IX_CAPITAL_SETTLEMENT");

                    b.ToTable("Capitals", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Code");

                    b.Property<byte[]>("Anthem")
                        .HasColumnType("bytea")
                        .HasColumnName("Anthem");

                    b.Property<decimal?>("CallingCode")
                        .HasColumnType("numeric(5,0)")
                        .HasColumnName("CallingCode");

                    b.Property<int?>("CapitalSettlementCode")
                        .HasColumnType("int")
                        .HasColumnName("CapitalSettlementCode");

                    b.Property<byte[]>("CoatOfArms")
                        .HasColumnType("bytea")
                        .HasColumnName("CoatOfArms");

                    b.Property<byte[]>("Flag")
                        .HasColumnType("bytea")
                        .HasColumnName("Flag");

                    b.Property<DateTime>("FoundingDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("FoundingDate");

                    b.Property<string>("GovernmentTypeCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("GovernmentTypeCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_COUNTRY");

                    b.HasIndex("GovernmentTypeCode")
                        .HasDatabaseName("IX_COUNTRY_GOVERNMENT_TYPE");

                    b.HasIndex("Code", "CapitalSettlementCode")
                        .HasDatabaseName("IX_COUNTRY_CAPITAL_SETTLEMENT");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.CountryComposition", b =>
                {
                    b.Property<string>("MemberCountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("MemberCountryCode");

                    b.Property<string>("UnionCountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("UnionCountryCode");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("MemberCountryCode", "UnionCountryCode", "SequenceNumber")
                        .HasName("PK_COUNTRY_COMPOSITION");

                    b.HasIndex("MemberCountryCode")
                        .HasDatabaseName("IX_COUNTRY_COMPOSITION_MEMBER_COUNTRY");

                    b.HasIndex("UnionCountryCode")
                        .HasDatabaseName("IX_COUNTRY_COMPOSITION_UNION_COUNTRY");

                    b.ToTable("CountryCompositions", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.GovernmentHistory", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<string>("GovernmentTypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("GovernmentTypeCode");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("CountryCode", "SequenceNumber")
                        .HasName("PK_GOVERNMENT_HISTORY");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("IX_GOVERNMENT_HISTORY_COUNTRY");

                    b.HasIndex("GovernmentTypeCode")
                        .HasDatabaseName("IX_GOVERNMENT_HISTORY_GOVERNMENT_TYPE");

                    b.ToTable("GovernmentHistories", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.GovernmentType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_GOVERNMENT_TYPE");

                    b.ToTable("GovernmentTypes", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.HealthInstitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Address");

                    b.Property<int?>("BedCount")
                        .HasColumnType("int")
                        .HasColumnName("BedCount");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<DateTime?>("FoundingDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("FoundingDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(30)")
                        .HasColumnName("Phone");

                    b.Property<int>("SettlementCode")
                        .HasColumnType("int")
                        .HasColumnName("SettlementCode");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TypeCode");

                    b.HasKey("Id")
                        .HasName("PK_HealthInstitutions");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("IX_HealthInstitution_CountryCode");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("IX_HealthInstitution_TypeCode");

                    b.HasIndex("CountryCode", "SettlementCode")
                        .HasDatabaseName("IX_HealthInstitution_Settlement");

                    b.ToTable("HealthInstitutions", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.HealthInstitutionType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_HealthInstitutionTypes");

                    b.ToTable("HealthInstitutionTypes", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.LegalSuccessor", b =>
                {
                    b.Property<string>("PredecessorCountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("PredecessorCountryCode");

                    b.Property<string>("SuccessorCountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("SuccessorCountryCode");

                    b.HasKey("PredecessorCountryCode", "SuccessorCountryCode")
                        .HasName("PK_LEGAL_SUCCESSOR");

                    b.HasIndex("PredecessorCountryCode")
                        .HasDatabaseName("IX_LEGAL_SUCCESSOR_PREDECESSOR_COUNTRY");

                    b.HasIndex("SuccessorCountryCode")
                        .HasDatabaseName("IX_LEGAL_SUCCESSOR_SUCCESSOR_COUNTRY");

                    b.ToTable("LegalSuccessors", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.LocalCommunity", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<decimal>("MunicipalityCode")
                        .HasColumnType("numeric(3,0)")
                        .HasColumnName("MunicipalityCode");

                    b.Property<decimal>("Identifier")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("Identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.Property<int?>("OfficeSettlementCode")
                        .HasColumnType("int")
                        .HasColumnName("OfficeSettlementCode");

                    b.HasKey("CountryCode", "MunicipalityCode", "Identifier")
                        .HasName("PK_LOCAL_COMMUNITY");

                    b.HasIndex("CountryCode", "MunicipalityCode")
                        .HasDatabaseName("IX_LOCAL_COMMUNITY_MUNICIPALITY");

                    b.HasIndex("CountryCode", "OfficeSettlementCode")
                        .HasDatabaseName("IX_LOCAL_COMMUNITY_OFFICE_SETTLEMENT");

                    b.ToTable("LocalCommunities", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.LocalCommunityCoverage", b =>
                {
                    b.Property<decimal>("MunicipalityCode")
                        .HasColumnType("numeric(3,0)")
                        .HasColumnName("MunicipalityCode");

                    b.Property<decimal>("LocalCommunityIdentifier")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("LocalCommunityIdentifier");

                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<int>("SettlementCode")
                        .HasColumnType("int")
                        .HasColumnName("SettlementCode");

                    b.HasKey("MunicipalityCode", "LocalCommunityIdentifier", "CountryCode", "SettlementCode")
                        .HasName("PK_LOCAL_COMMUNITY_COVERAGE");

                    b.HasIndex("CountryCode", "SettlementCode")
                        .HasDatabaseName("IX_LOCAL_COMMUNITY_COVERAGE_SETTLEMENT");

                    b.HasIndex("CountryCode", "MunicipalityCode", "LocalCommunityIdentifier")
                        .HasDatabaseName("IX_LOCAL_COMMUNITY_COVERAGE_LOCAL_COMMUNITY");

                    b.ToTable("LocalCommunityCoverages", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Municipality", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<decimal>("Code")
                        .HasColumnType("numeric(3,0)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.Property<int?>("SeatSettlementCode")
                        .HasColumnType("int")
                        .HasColumnName("SeatSettlementCode");

                    b.HasKey("CountryCode", "Code")
                        .HasName("PK_MUNICIPALITY");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("IX_MUNICIPALITY_COUNTRY");

                    b.HasIndex("CountryCode", "SeatSettlementCode")
                        .HasDatabaseName("IX_MUNICIPALITY_SEAT_SETTLEMENT");

                    b.ToTable("Municipalities", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.MunicipalitySettlementCoverage", b =>
                {
                    b.Property<decimal>("MunicipalityCode")
                        .HasColumnType("numeric(3,0)")
                        .HasColumnName("MunicipalityCode");

                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<int>("SettlementCode")
                        .HasColumnType("int")
                        .HasColumnName("SettlementCode");

                    b.HasKey("MunicipalityCode", "CountryCode", "SettlementCode")
                        .HasName("PK_MUNICIPALITY_SETTLEMENT_COVERAGE");

                    b.HasIndex("CountryCode", "MunicipalityCode")
                        .HasDatabaseName("IX_MUNICIPALITY_SETTLEMENT_COVERAGE_MUNICIPALITY");

                    b.HasIndex("CountryCode", "SettlementCode")
                        .HasDatabaseName("IX_MUNICIPALITY_SETTLEMENT_COVERAGE_SETTLEMENT");

                    b.ToTable("MunicipalitySettlementCoverages", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Region", b =>
                {
                    b.Property<string>("TypeCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TypeCode");

                    b.Property<short>("Code")
                        .HasColumnType("smallint")
                        .HasColumnName("Code");

                    b.Property<int?>("AdministrativeSeatSettlementCode")
                        .HasColumnType("int")
                        .HasColumnName("AdministrativeSeatSettlementCode");

                    b.Property<string>("BelongsToCountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("BelongsToCountryCode");

                    b.Property<string>("HeadquartersCountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("HeadquartersCountryCode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("TypeCode", "Code")
                        .HasName("PK_REGION");

                    b.HasIndex("BelongsToCountryCode")
                        .HasDatabaseName("IX_REGION_COUNTRY");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("IX_REGION_TYPE");

                    b.HasIndex("HeadquartersCountryCode", "AdministrativeSeatSettlementCode")
                        .HasDatabaseName("IX_REGION_ADMINISTRATIVE_SEAT_SETTLEMENT");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.RegionComposition", b =>
                {
                    b.Property<string>("ParentRegionTypeCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ParentRegionTypeCode");

                    b.Property<short>("ParentRegionCode")
                        .HasColumnType("smallint")
                        .HasColumnName("ParentRegionCode");

                    b.Property<string>("MemberRegionTypeCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MemberRegionTypeCode");

                    b.Property<short>("MemberRegionCode")
                        .HasColumnType("smallint")
                        .HasColumnName("MemberRegionCode");

                    b.HasKey("ParentRegionTypeCode", "ParentRegionCode", "MemberRegionTypeCode", "MemberRegionCode")
                        .HasName("PK_REGION_COMPOSITION");

                    b.HasIndex("MemberRegionTypeCode", "MemberRegionCode")
                        .HasDatabaseName("IX_REGION_COMPOSITION_MEMBER_REGION");

                    b.HasIndex("ParentRegionTypeCode", "ParentRegionCode")
                        .HasDatabaseName("IX_REGION_COMPOSITION_PARENT_REGION");

                    b.ToTable("RegionCompositions", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.RegionSettlementCoverage", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<int>("SettlementCode")
                        .HasColumnType("int")
                        .HasColumnName("SettlementCode");

                    b.Property<string>("RegionTypeCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("RegionTypeCode");

                    b.Property<short>("RegionCode")
                        .HasColumnType("smallint")
                        .HasColumnName("RegionCode");

                    b.HasKey("CountryCode", "SettlementCode", "RegionTypeCode", "RegionCode")
                        .HasName("PK_REGION_SETTLEMENT_COVERAGE");

                    b.HasIndex("CountryCode", "SettlementCode")
                        .HasDatabaseName("IX_REGION_SETTLEMENT_COVERAGE_SETTLEMENT");

                    b.HasIndex("RegionTypeCode", "RegionCode")
                        .HasDatabaseName("IX_REGION_SETTLEMENT_COVERAGE_REGION");

                    b.ToTable("RegionSettlementCoverages", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.RegionType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(265)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_REGION_TYPE");

                    b.ToTable("RegionTypes", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Settlement", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(3)")
                        .HasColumnName("CountryCode");

                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.Property<string>("PostalCode")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("PostalCode");

                    b.HasKey("CountryCode", "Code")
                        .HasName("PK_SETTLEMENT");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("IX_SETTLEMENT_COUNTRY");

                    b.ToTable("Settlements", (string)null);
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Capital", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Country", "Country")
                        .WithMany("CapitalHistory")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CAPITAL_COUNTRY");

                    b.HasOne("LocationService.Domain.Entities.Settlement", "Settlement")
                        .WithMany("CapitalOf")
                        .HasForeignKey("CountryCode", "SettlementCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CAPITAL_SETTLEMENT");

                    b.Navigation("Country");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Country", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.GovernmentType", "GovernmentType")
                        .WithMany("Countries")
                        .HasForeignKey("GovernmentTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_COUNTRY_GOVERNMENT_TYPE");

                    b.HasOne("LocationService.Domain.Entities.Settlement", "CapitalSettlement")
                        .WithMany()
                        .HasForeignKey("Code", "CapitalSettlementCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_COUNTRY_CAPITAL_SETTLEMENT");

                    b.Navigation("CapitalSettlement");

                    b.Navigation("GovernmentType");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.CountryComposition", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Country", "MemberCountry")
                        .WithMany("MemberOfUnions")
                        .HasForeignKey("MemberCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_COUNTRY_COMPOSITION_MEMBER_COUNTRY");

                    b.HasOne("LocationService.Domain.Entities.Country", "UnionCountry")
                        .WithMany("UnionMembers")
                        .HasForeignKey("UnionCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_COUNTRY_COMPOSITION_UNION_COUNTRY");

                    b.Navigation("MemberCountry");

                    b.Navigation("UnionCountry");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.GovernmentHistory", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Country", "Country")
                        .WithMany("GovernmentHistory")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GOVERNMENT_HISTORY_COUNTRY");

                    b.HasOne("LocationService.Domain.Entities.GovernmentType", "GovernmentType")
                        .WithMany("History")
                        .HasForeignKey("GovernmentTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GOVERNMENT_HISTORY_GOVERNMENT_TYPE");

                    b.Navigation("Country");

                    b.Navigation("GovernmentType");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.HealthInstitution", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Country", "Country")
                        .WithMany("HealthInstitutions")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HealthInstitution_Country");

                    b.HasOne("LocationService.Domain.Entities.HealthInstitutionType", "Type")
                        .WithMany("HealthInstitutions")
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HealthInstitution_HealthInstitutionType");

                    b.HasOne("LocationService.Domain.Entities.Settlement", "Settlement")
                        .WithMany("HealthInstitutions")
                        .HasForeignKey("CountryCode", "SettlementCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_HealthInstitution_Settlement");

                    b.Navigation("Country");

                    b.Navigation("Settlement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.LegalSuccessor", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Country", "PredecessorCountry")
                        .WithMany("PredecessorOf")
                        .HasForeignKey("PredecessorCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LEGAL_SUCCESSOR_PREDECESSOR_COUNTRY");

                    b.HasOne("LocationService.Domain.Entities.Country", "SuccessorCountry")
                        .WithMany("SuccessorOf")
                        .HasForeignKey("SuccessorCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LEGAL_SUCCESSOR_SUCCESSOR_COUNTRY");

                    b.Navigation("PredecessorCountry");

                    b.Navigation("SuccessorCountry");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.LocalCommunity", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Municipality", "Municipality")
                        .WithMany("LocalCommunities")
                        .HasForeignKey("CountryCode", "MunicipalityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LOCAL_COMMUNITY_MUNICIPALITY");

                    b.HasOne("LocationService.Domain.Entities.Settlement", "OfficeSettlement")
                        .WithMany("LocalCommunityOffices")
                        .HasForeignKey("CountryCode", "OfficeSettlementCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_LOCAL_COMMUNITY_OFFICE_SETTLEMENT");

                    b.Navigation("Municipality");

                    b.Navigation("OfficeSettlement");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.LocalCommunityCoverage", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Settlement", "Settlement")
                        .WithMany("LocalCommunityCoverages")
                        .HasForeignKey("CountryCode", "SettlementCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LOCAL_COMMUNITY_COVERAGE_SETTLEMENT");

                    b.HasOne("LocationService.Domain.Entities.LocalCommunity", "LocalCommunity")
                        .WithMany("Coverages")
                        .HasForeignKey("CountryCode", "MunicipalityCode", "LocalCommunityIdentifier")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LOCAL_COMMUNITY_COVERAGE_LOCAL_COMMUNITY");

                    b.Navigation("LocalCommunity");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Municipality", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Country", "Country")
                        .WithMany("Municipalities")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MUNICIPALITY_COUNTRY");

                    b.HasOne("LocationService.Domain.Entities.Settlement", "SeatSettlement")
                        .WithMany("MunicipalitySeatOf")
                        .HasForeignKey("CountryCode", "SeatSettlementCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_MUNICIPALITY_SEAT_SETTLEMENT");

                    b.Navigation("Country");

                    b.Navigation("SeatSettlement");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.MunicipalitySettlementCoverage", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Municipality", "Municipality")
                        .WithMany("Settlements")
                        .HasForeignKey("CountryCode", "MunicipalityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MUNICIPALITY_SETTLEMENT_COVERAGE_MUNICIPALITY");

                    b.HasOne("LocationService.Domain.Entities.Settlement", "Settlement")
                        .WithMany("MunicipalityCoverages")
                        .HasForeignKey("CountryCode", "SettlementCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MUNICIPALITY_SETTLEMENT_COVERAGE_SETTLEMENT");

                    b.Navigation("Municipality");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Region", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Country", "BelongsToCountry")
                        .WithMany("HomeRegions")
                        .HasForeignKey("BelongsToCountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_REGION_COUNTRY");

                    b.HasOne("LocationService.Domain.Entities.RegionType", "Type")
                        .WithMany("Regions")
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_REGION_TYPE");

                    b.HasOne("LocationService.Domain.Entities.Settlement", "AdministrativeSeatSettlement")
                        .WithMany("RegionAdministrativeSeatOf")
                        .HasForeignKey("HeadquartersCountryCode", "AdministrativeSeatSettlementCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_REGION_ADMINISTRATIVE_SEAT_SETTLEMENT");

                    b.Navigation("AdministrativeSeatSettlement");

                    b.Navigation("BelongsToCountry");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.RegionComposition", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Region", "MemberRegion")
                        .WithMany("AsMemberOf")
                        .HasForeignKey("MemberRegionTypeCode", "MemberRegionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_REGION_COMPOSITION_MEMBER_REGION");

                    b.HasOne("LocationService.Domain.Entities.Region", "ParentRegion")
                        .WithMany("AsParentOf")
                        .HasForeignKey("ParentRegionTypeCode", "ParentRegionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_REGION_COMPOSITION_PARENT_REGION");

                    b.Navigation("MemberRegion");

                    b.Navigation("ParentRegion");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.RegionSettlementCoverage", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Settlement", "Settlement")
                        .WithMany("RegionCoverages")
                        .HasForeignKey("CountryCode", "SettlementCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_REGION_SETTLEMENT_COVERAGE_SETTLEMENT");

                    b.HasOne("LocationService.Domain.Entities.Region", "Region")
                        .WithMany("SettlementCoverages")
                        .HasForeignKey("RegionTypeCode", "RegionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_REGION_SETTLEMENT_COVERAGE_REGION");

                    b.Navigation("Region");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Settlement", b =>
                {
                    b.HasOne("LocationService.Domain.Entities.Country", "Country")
                        .WithMany("Settlements")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_SETTLEMENT_COUNTRY");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Country", b =>
                {
                    b.Navigation("CapitalHistory");

                    b.Navigation("GovernmentHistory");

                    b.Navigation("HealthInstitutions");

                    b.Navigation("HomeRegions");

                    b.Navigation("MemberOfUnions");

                    b.Navigation("Municipalities");

                    b.Navigation("PredecessorOf");

                    b.Navigation("Settlements");

                    b.Navigation("SuccessorOf");

                    b.Navigation("UnionMembers");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.GovernmentType", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("History");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.HealthInstitutionType", b =>
                {
                    b.Navigation("HealthInstitutions");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.LocalCommunity", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Municipality", b =>
                {
                    b.Navigation("LocalCommunities");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Region", b =>
                {
                    b.Navigation("AsMemberOf");

                    b.Navigation("AsParentOf");

                    b.Navigation("SettlementCoverages");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.RegionType", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("LocationService.Domain.Entities.Settlement", b =>
                {
                    b.Navigation("CapitalOf");

                    b.Navigation("HealthInstitutions");

                    b.Navigation("LocalCommunityCoverages");

                    b.Navigation("LocalCommunityOffices");

                    b.Navigation("MunicipalityCoverages");

                    b.Navigation("MunicipalitySeatOf");

                    b.Navigation("RegionAdministrativeSeatOf");

                    b.Navigation("RegionCoverages");
                });
#pragma warning restore 612, 618
        }
    }
}
