// <auto-generated />
using System;
using DoctorService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DoctorService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DoctorDbContext))]
    partial class DoctorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoctorService.Domain.Entities.DegreeType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_DEGREE_TYPE");

                    b.ToTable("DegreeTypes", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("AverageRating");

                    b.Property<string>("Bio")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("Bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("CurrentHealthInstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("CurrentHealthInstitutionId");

                    b.Property<string>("CurrentInstitutionName")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("CurrentInstitutionName");

                    b.Property<string>("CurrentSpecializationCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CurrentSpecializationCode");

                    b.Property<string>("CurrentStatusCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CurrentStatusCode");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("IsAvailable");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp")
                        .HasColumnName("LastActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("LicenseAuthorityCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("LicenseAuthorityCode");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LicenseNumber");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Phone");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ProfilePictureUrl");

                    b.Property<int>("TotalReviews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TotalReviews");

                    b.HasKey("Id")
                        .HasName("PK_DOCTOR");

                    b.HasIndex("CurrentSpecializationCode")
                        .HasDatabaseName("IX_DOCTOR_SPECIALIZATION");

                    b.HasIndex("CurrentStatusCode")
                        .HasDatabaseName("IX_DOCTOR_STATUS");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_DOCTOR_EMAIL");

                    b.HasIndex("LastName")
                        .HasDatabaseName("IX_DOCTOR_LASTNAME");

                    b.HasIndex("LicenseAuthorityCode")
                        .HasDatabaseName("IX_DOCTOR_LICENSE_AUTHORITY");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_DOCTOR_LICENSE");

                    b.HasIndex("IsAvailable", "CurrentStatusCode")
                        .HasDatabaseName("IX_DOCTOR_AVAILABLE_STATUS");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorAffiliationHistory", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<int?>("HealthInstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("HealthInstitutionId");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("InstitutionName");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("DoctorId", "SequenceNumber")
                        .HasName("PK_DOCTOR_AFFILIATION_HISTORY");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_DOCTOR_AFFILIATION_HISTORY_DOCTOR");

                    b.ToTable("DoctorAffiliationHistories", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorDegreeCoverage", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<string>("DegreeTypeCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DegreeTypeCode");

                    b.Property<string>("InstitutionName")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("InstitutionName");

                    b.Property<decimal?>("Year")
                        .HasColumnType("numeric(4,0)")
                        .HasColumnName("Year");

                    b.HasKey("DoctorId", "DegreeTypeCode")
                        .HasName("PK_DOCTOR_DEGREE_COVERAGE");

                    b.HasIndex("DegreeTypeCode")
                        .HasDatabaseName("IX_DOCTOR_DEGREE_COVERAGE_DEGREE_TYPE");

                    b.ToTable("DoctorDegreeCoverages", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorLanguageCoverage", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("LanguageCode");

                    b.HasKey("DoctorId", "LanguageCode")
                        .HasName("PK_DOCTOR_LANGUAGE_COVERAGE");

                    b.HasIndex("LanguageCode")
                        .HasDatabaseName("IX_DOCTOR_LANGUAGE_COVERAGE_LANGUAGE");

                    b.ToTable("DoctorLanguageCoverages", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorLicenseHistory", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<string>("LicenseAuthorityCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("LicenseAuthorityCode");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("LicenseNumber");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("DoctorId", "SequenceNumber")
                        .HasName("PK_DOCTOR_LICENSE_HISTORY");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_DOCTOR_LICENSE_HISTORY_DOCTOR");

                    b.HasIndex("LicenseAuthorityCode")
                        .HasDatabaseName("IX_DOCTOR_LICENSE_HISTORY_AUTHORITY");

                    b.ToTable("DoctorLicenseHistories", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorReview", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<string>("Comment")
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("Rating");

                    b.Property<Guid?>("ReviewerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("ReviewerUserId");

                    b.HasKey("DoctorId", "SequenceNumber")
                        .HasName("PK_DOCTOR_REVIEW");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_DOCTOR_REVIEW_DOCTOR");

                    b.ToTable("DoctorReviews", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorSpecializationCoverage", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<string>("SpecializationCode")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SpecializationCode");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("IsPrimary");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("DoctorId", "SpecializationCode")
                        .HasName("PK_DOCTOR_SPECIALIZATION_COVERAGE");

                    b.HasIndex("SpecializationCode")
                        .HasDatabaseName("IX_DOCTOR_SPECIALIZATION_COVERAGE_SPECIALIZATION");

                    b.ToTable("DoctorSpecializationCoverages", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_DOCTOR_STATUS");

                    b.ToTable("DoctorStatuses", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorStatusHistory", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp")
                        .HasColumnName("From");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("StatusCode");

                    b.Property<DateTime?>("To")
                        .HasColumnType("timestamp")
                        .HasColumnName("To");

                    b.HasKey("DoctorId", "SequenceNumber")
                        .HasName("PK_DOCTOR_STATUS_HISTORY");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_DOCTOR_STATUS_HISTORY_DOCTOR");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("IX_DOCTOR_STATUS_HISTORY_STATUS");

                    b.ToTable("DoctorStatusHistories", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_LANGUAGE");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.LicenseAuthority", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_LICENSE_AUTHORITY");

                    b.ToTable("LicenseAuthorities", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.Specialization", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_SPECIALIZATION");

                    b.ToTable("Specializations", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.WorkingSlot", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("DayOfWeek");

                    b.Property<decimal>("SequenceNumber")
                        .HasColumnType("numeric(2,0)")
                        .HasColumnName("SequenceNumber");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time")
                        .HasColumnName("End");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time")
                        .HasColumnName("Start");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp")
                        .HasColumnName("ValidFrom");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp")
                        .HasColumnName("ValidTo");

                    b.HasKey("DoctorId", "DayOfWeek", "SequenceNumber")
                        .HasName("PK_WORKING_SLOT");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("IX_WORKING_SLOT_DOCTOR");

                    b.ToTable("WorkingSlots", (string)null);
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("DoctorService.Domain.Entities.Specialization", "CurrentSpecialization")
                        .WithMany("Doctors")
                        .HasForeignKey("CurrentSpecializationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_SPECIALIZATION");

                    b.HasOne("DoctorService.Domain.Entities.DoctorStatus", "Status")
                        .WithMany("Doctors")
                        .HasForeignKey("CurrentStatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_STATUS");

                    b.HasOne("DoctorService.Domain.Entities.LicenseAuthority", "LicenseAuthority")
                        .WithMany("Doctors")
                        .HasForeignKey("LicenseAuthorityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DOCTOR_LICENSE_AUTHORITY");

                    b.Navigation("CurrentSpecialization");

                    b.Navigation("LicenseAuthority");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorAffiliationHistory", b =>
                {
                    b.HasOne("DoctorService.Domain.Entities.Doctor", "Doctor")
                        .WithMany("AffiliationHistories")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_AFFILIATION_HISTORY_DOCTOR");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorDegreeCoverage", b =>
                {
                    b.HasOne("DoctorService.Domain.Entities.DegreeType", "DegreeType")
                        .WithMany("Coverages")
                        .HasForeignKey("DegreeTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_DEGREE_COVERAGE_DEGREE_TYPE");

                    b.HasOne("DoctorService.Domain.Entities.Doctor", "Doctor")
                        .WithMany("DegreeCoverages")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_DEGREE_COVERAGE_DOCTOR");

                    b.Navigation("DegreeType");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorLanguageCoverage", b =>
                {
                    b.HasOne("DoctorService.Domain.Entities.Doctor", "Doctor")
                        .WithMany("LanguageCoverages")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_LANGUAGE_COVERAGE_DOCTOR");

                    b.HasOne("DoctorService.Domain.Entities.Language", "Language")
                        .WithMany("Coverages")
                        .HasForeignKey("LanguageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_LANGUAGE_COVERAGE_LANGUAGE");

                    b.Navigation("Doctor");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorLicenseHistory", b =>
                {
                    b.HasOne("DoctorService.Domain.Entities.Doctor", "Doctor")
                        .WithMany("LicenseHistories")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_LICENSE_HISTORY_DOCTOR");

                    b.HasOne("DoctorService.Domain.Entities.LicenseAuthority", "LicenseAuthority")
                        .WithMany("Histories")
                        .HasForeignKey("LicenseAuthorityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_DOCTOR_LICENSE_HISTORY_AUTHORITY");

                    b.Navigation("Doctor");

                    b.Navigation("LicenseAuthority");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorReview", b =>
                {
                    b.HasOne("DoctorService.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Reviews")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_REVIEW_DOCTOR");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorSpecializationCoverage", b =>
                {
                    b.HasOne("DoctorService.Domain.Entities.Doctor", "Doctor")
                        .WithMany("SpecializationCoverages")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_SPECIALIZATION_COVERAGE_DOCTOR");

                    b.HasOne("DoctorService.Domain.Entities.Specialization", "Specialization")
                        .WithMany("Coverages")
                        .HasForeignKey("SpecializationCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_SPECIALIZATION_COVERAGE_SPECIALIZATION");

                    b.Navigation("Doctor");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorStatusHistory", b =>
                {
                    b.HasOne("DoctorService.Domain.Entities.Doctor", "Doctor")
                        .WithMany("StatusHistories")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_STATUS_HISTORY_DOCTOR");

                    b.HasOne("DoctorService.Domain.Entities.DoctorStatus", "Status")
                        .WithMany("Histories")
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DOCTOR_STATUS_HISTORY_STATUS");

                    b.Navigation("Doctor");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.WorkingSlot", b =>
                {
                    b.HasOne("DoctorService.Domain.Entities.Doctor", "Doctor")
                        .WithMany("WorkingSlots")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WORKING_SLOT_DOCTOR");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DegreeType", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("AffiliationHistories");

                    b.Navigation("DegreeCoverages");

                    b.Navigation("LanguageCoverages");

                    b.Navigation("LicenseHistories");

                    b.Navigation("Reviews");

                    b.Navigation("SpecializationCoverages");

                    b.Navigation("StatusHistories");

                    b.Navigation("WorkingSlots");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.DoctorStatus", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.Language", b =>
                {
                    b.Navigation("Coverages");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.LicenseAuthority", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("DoctorService.Domain.Entities.Specialization", b =>
                {
                    b.Navigation("Coverages");

                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
