global using BuildingBlocks.Exceptions.Handler;
global using BuildingBlocks.Logging;
global using LocationService.Application;
global using LocationService.Infrastructure;
global using LocationService.Infrastructure.Persistence;
global using LocationService.Infrastructure.Seeding;
global using Microsoft.EntityFrameworkCore;
global using Scalar.AspNetCore;
global using Serilog;
