// <auto-generated />
using System;
using AppointmentService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppointmentService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    partial class AppointmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppointmentService.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("CancelledAt");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("CompletedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("DoctorId");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("EndsAt");

                    b.Property<int?>("HealthInstitutionId")
                        .HasColumnType("int")
                        .HasColumnName("HealthInstitutionId");

                    b.Property<string>("Notes")
                        .HasColumnType("varchar(512)")
                        .HasColumnName("Notes");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("PatientId");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("StartsAt");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("StatusCode");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Title");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("TypeCode");

                    b.HasKey("Id")
                        .HasName("PK_APPOINTMENT");

                    b.HasIndex("StatusCode")
                        .HasDatabaseName("IX_APPOINTMENT_STATUS");

                    b.HasIndex("TypeCode")
                        .HasDatabaseName("IX_APPOINTMENT_TYPE");

                    b.HasIndex("DoctorId", "StartsAt")
                        .HasDatabaseName("IX_APPOINTMENT_DOCTOR_START");

                    b.HasIndex("PatientId", "StartsAt")
                        .HasDatabaseName("IX_APPOINTMENT_PATIENT_START");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("AppointmentService.Domain.Entities.AppointmentStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_APPOINTMENT_STATUS");

                    b.ToTable("AppointmentStatuses", (string)null);
                });

            modelBuilder.Entity("AppointmentService.Domain.Entities.AppointmentType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Code")
                        .HasName("PK_APPOINTMENT_TYPE");

                    b.ToTable("AppointmentTypes", (string)null);
                });

            modelBuilder.Entity("AppointmentService.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("AppointmentService.Domain.Entities.AppointmentStatus", "Status")
                        .WithMany("Appointments")
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_APPOINTMENT_STATUS");

                    b.HasOne("AppointmentService.Domain.Entities.AppointmentType", "Type")
                        .WithMany("Appointments")
                        .HasForeignKey("TypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_APPOINTMENT_TYPE");

                    b.Navigation("Status");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("AppointmentService.Domain.Entities.AppointmentStatus", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("AppointmentService.Domain.Entities.AppointmentType", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
